---
- name: check if file already exists
  stat:
    path: "{{ item.path }}"
  register: file_stat
  loop:
    - "{{ users.admin1 }}"
    - "{{ users.root }}"

- name: remove file if exists
  file:
    path: "{{ item.value.path }}"
    state: absent
  loop: "{{ users | dict2items }}"
  when: item.value.path is file

- name: copy new file to host
  copy:
    src: "{{ source }}"
    dest: "{{ item.dest }}"
    mode: '0744'
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  loop:
    - "{{ users.admin1 }}"
    - "{{ users.root }}"

- name: set file in .bashrc
  lineinfile:
    path: "{{ item.dest }}/.bashrc"
    line: "bash .dymotd.sh"
    insertbefore: BOF
  loop:
    - "{{ users.admin1 }}"
    - "{{ users.root }}"
