- name: Generate a password                                  
  set_fact:                                                  
    password: "{{ lookup('community.general.random_string', length=12, min_lower=1, min_upper=1, min_numeric=1, min_special=1, override_special='!#*%&') }}"
                                                             
- name: Set new password for users
  user:
    name: "{{ item }}"
    password: "{[ password | password_hash('sha512') }}"
  loop: "{{ users }}"

- name: Return new password
  set_fact:
    created_password: "{{ password }}"
