- name: Create timestamp
  set_fact:
    date: "{{ '%Y-%m-%d' | strftime }}"
  changed_when: false

- name: Get password expiration in days
  block:
    - name: Calculate expire date into days$
      shell: |
        password_expire="$(sudo chage -l "{{ item }}" | awk -F ': ' '/Password expires/ {print $2}')"

        if [[ "$password_expire" == "never" ]]; then
          echo "never"
        else
          echo $(( ( $(date -d "$password_expire" +%s) - $(date +%s) ) / 86400 ))
        fi
      loop: "{{ users }}"
      register: expire_days
      changed_when: false

    - name: Filter the users
      set_fact:
        expire_users: "{{ expiring_users | default([]) + [item.item] }}"
      loop: "{{ expire_days.results }}"
      when: item.stdout | int <= 7
      changed_when: false

- name: Create data sheet
  block:
    - name: Create header line in data file
      lineinfile:
        path: "/path/to/data/file/password-{{ date }}.csv"
        line: "Username,Host,Days until expiration"
        create: yes
        mode: '0644'
        state: present
      delegate_to: localhost

    - name: Create list with all passwords where expire is <7 days
      lineinfile:
        path: "/path/to/data/file/password-{{ date }}.csv"
        line: "{{ item.item }},{{ ansible_host }}"
        create: yes
        mode: '0644'
      loop: "{{ expire_days.results }}"
      delegate_to: localhost
      changed_when: false

- name: Create randomized password
  include_tasks: create_psw.yml
  loop: "{{ expire_days.results }}"
  when: item.stdout | int <= 7
  loop_control:
    label: "{{ item.item }}"

- name: Append new passwords to the data sheet
  lineinfile:
    path: "/path/to/data/file/password-{{ date }}.csv"
    line: "{{ item.item }},{{ ansible_host }},{{ created_password }}"
    create: yes
    mode: '0644'
  loop: "{{ expire_days.results }}"
  when: item.stdout | int <= 7
  delegate_to: localhost

- name: Create & run DB inserts
  include_tasks: db_insert.yml
