- name: Get password expiration in days
  block:
    - name: Calculate expire date into days$
      shell: |
        password_expire="$(LANG=en_US sudo chage -l "{{ item }}" | awk -F ': ' '/Password expires/ {print $2}')"

        if [[ "$password_expire" == "never" ]]; then
          echo "999"
        else
          echo $(( ( $(date -d "$password_expire" +%s) - $(date +%s) ) / 86400 ))
        fi
      args:
        executable: /bin/bash
      loop: "{{ users }}"
      register: expire_days
      changed_when: false

- name: Create data sheet
  block:
    - name: Create header line in data file
      lineinfile:
        path: "{{ tmpfile }}"
        line: "Username,Host,Password"
        create: yes
        mode: '0644'
        state: present
      delegate_to: localhost
      changed_when: false

- name: Create password
  block:
    - name: Generate password for each user
      set_fact:
        user_passwords: "{{ user_passwords | default({}) | combine({ item.item: lookup('community.general.random_string', length=password_length, min_lower=password_min_lower, min_upper=password_min_upper, min_numeric=password_min_numeric, min_special=password_min_special, override_special=password_override_special) }) }}"
      loop: "{{ expire_days.results }}"
      when: item.stdout | int <= 7

    - name: Set new password for users
      user:
        name: "{{ item.item }}"
        password: "{{ user_passwords[item.item] | password_hash('sha512') }}"
      loop: "{{ expire_days.results }}"
      when: item.stdout | int <= 7

    - name: Return new password
      set_fact:
        created_password: "{{ user_passwords }}"
      when: user_passwords is defined
  
- name: Append new passwords to the data sheet
  lineinfile:
    path: "{{ tmpfile }}"
    line: "{{ item.item }},{{ inventory_hostname }},{{ created_password[item.item] }}"
    create: yes
    mode: '0644'
  loop: "{{ expire_days.results }}"
  when: item.stdout | int <= 7
  delegate_to: localhost

- name: Create & run DB inserts
  include_tasks: db_inserts.yml
